# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

decompress <- function(input) {
    .Call('_wobbegong_decompress', PACKAGE = 'wobbegong', input)
}

dump_list_of_vectors <- function(incoming, output_file) {
    .Call('_wobbegong_dump_list_of_vectors', PACKAGE = 'wobbegong', incoming, output_file)
}

dump_dense_rows <- function(mat, output_file, rtype) {
    .Call('_wobbegong_dump_dense_rows', PACKAGE = 'wobbegong', mat, output_file, rtype)
}

dump_sparse_rows <- function(mat, output_file, rtype) {
    .Call('_wobbegong_dump_sparse_rows', PACKAGE = 'wobbegong', mat, output_file, rtype)
}

get_byte_order <- function() {
    .Call('_wobbegong_get_byte_order', PACKAGE = 'wobbegong')
}

